version: "3.7"

services:
  php:
    container_name: php-fpm
    build: 
      context: .
      target: admin-ui-php-dev
    volumes:
      - ./src:/code
    networks:
        - mbc-local

  web-server:
    container_name: web-server
    build: 
      context: .
      target: admin-ui-nginx
    volumes:
      - ./src:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
        - mbc-local